# -*- coding: utf-8 -*-
from typing import Dict, Any

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

from mods_editor import mods_editor

mod_names_dict = {}
editor = mods_editor()

class Ui_Es_mod_namager_linux(object):
    def setupUi(self, Es_mod_namager_linux):
        Es_mod_namager_linux.setObjectName("Es_mod_namager_linux")
        Es_mod_namager_linux.resize(560, 600)

        self.centralwidget = QtWidgets.QWidget(Es_mod_namager_linux)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_Launch_es = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Launch_es.setGeometry(QtCore.QRect(430, 510, 120, 40))
        self.btn_Launch_es.setObjectName("btn_Launch_es")

        self.btn_update_mods_db = QtWidgets.QPushButton(self.centralwidget)
        self.btn_update_mods_db.setGeometry(QtCore.QRect(300, 510, 120, 40))
        self.btn_update_mods_db.setCheckable(False)
        self.btn_update_mods_db.setObjectName("btn_update_mods_db")
        self.btn_update_mods_db.clicked.connect(self.fill_mods_lists)

        self.enabled_mods_list = QtWidgets.QListWidget(self.centralwidget)
        self.enabled_mods_list.setGeometry(QtCore.QRect(10, 40, 260, 450))
        self.enabled_mods_list.setObjectName("enabled_mods_list")

        self.disabled_mods_list = QtWidgets.QListWidget(self.centralwidget)
        self.disabled_mods_list.setGeometry(QtCore.QRect(290, 40, 260, 450))
        self.disabled_mods_list.setObjectName("disabled_mods_list")

        self.enabled_mods_label = QtWidgets.QLabel(self.centralwidget)
        self.enabled_mods_label.setGeometry(QtCore.QRect(10, 10, 261, 31))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.enabled_mods_label.setFont(font)
        self.enabled_mods_label.setObjectName("enabled_mods_label")

        self.disabled_mods_label = QtWidgets.QLabel(self.centralwidget)
        self.disabled_mods_label.setGeometry(QtCore.QRect(290, 10, 261, 31))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.disabled_mods_label.setFont(font)
        self.disabled_mods_label.setObjectName("disabled_mods_label")

        Es_mod_namager_linux.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(Es_mod_namager_linux)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 30))
        self.menubar.setObjectName("menubar")

        self.settings_menu = QtWidgets.QMenu(self.menubar)
        self.settings_menu.setObjectName("settings_menu")

        self.abbout_menu = QtWidgets.QMenu(self.menubar)
        self.abbout_menu.setObjectName("abbout_menu")

        Es_mod_namager_linux.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Es_mod_namager_linux)
        self.statusbar.setObjectName("statusbar")
        Es_mod_namager_linux.setStatusBar(self.statusbar)

        self.mods_path_settings = QtWidgets.QAction(Es_mod_namager_linux)
        self.mods_path_settings.setObjectName("mods_path_settings")

        self.abbout_guide = QtWidgets.QAction(Es_mod_namager_linux)
        self.abbout_guide.setObjectName("abbout_guide")

        self.abbout_program = QtWidgets.QAction(Es_mod_namager_linux)
        self.abbout_program.setObjectName("abbout_program")

        self.settings_menu.addAction(self.mods_path_settings)

        self.abbout_menu.addAction(self.abbout_guide)
        self.abbout_menu.addAction(self.abbout_program)

        self.menubar.addAction(self.settings_menu.menuAction())
        self.menubar.addAction(self.abbout_menu.menuAction())

        self.retranslateUi(Es_mod_namager_linux)
        QtCore.QMetaObject.connectSlotsByName(Es_mod_namager_linux)

        self.enabled_mods_list.itemDoubleClicked.connect(self.clicked_item_replace)
        self.disabled_mods_list.itemDoubleClicked.connect(self.clicked_item_replace)

        editor.load_mods_db()
        self.fill_mods_lists()

    def fill_mods_lists(self):
        editor.check_new_mods()
        global mod_names_dict

        self.enabled_mods_list.clear()
        self.disabled_mods_list.clear()
        with open("/home/skiyman/programming/pythonProject/ES_mod_manager_linux/mods_db.json", "r+") as file:
            mods_db = json.load(file)

        self.enabled_mods_list.setSortingEnabled(True)
        self.disabled_mods_list.setSortingEnabled(True)

        for mod in mods_db:
            if mods_db[mod]['Work_status'] == "Enabled":
                mod_names_dict[mods_db[mod]["mod_name"]] = mod
                self.enabled_mods_list.addItem(mods_db[mod]['mod_name'])
            else:
                mod_names_dict[mods_db[mod]["mod_name"]] = mod
                self.disabled_mods_list.addItem(mods_db[mod]['mod_name'])



    def clicked_item_replace(self, item):
        editor.mod_replace(mod_names_dict[item.text()])
        self.fill_mods_lists()




    def retranslateUi(self, Es_mod_namager_linux):
        _translate = QtCore.QCoreApplication.translate
        Es_mod_namager_linux.setWindowTitle(_translate("Es_mod_namager_linux", "MainWindow"))
        self.btn_Launch_es.setText(_translate("Es_mod_namager_linux", "Launch ES"))
        self.btn_update_mods_db.setText(_translate("Es_mod_namager_linux", "Update mods db"))
        self.enabled_mods_label.setText(_translate("Es_mod_namager_linux", "Enabled mods"))
        self.disabled_mods_label.setText(_translate("Es_mod_namager_linux", "Disabled mods"))
        self.settings_menu.setTitle(_translate("Es_mod_namager_linux", "Настройки"))
        self.abbout_menu.setTitle(_translate("Es_mod_namager_linux", "Справка"))
        self.mods_path_settings.setText(_translate("Es_mod_namager_linux", "Пути"))
        self.abbout_guide.setText(_translate("Es_mod_namager_linux", "Справка по использованию"))
        self.abbout_program.setText(_translate("Es_mod_namager_linux", "О мненджере"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Es_mod_namager_linux = QtWidgets.QMainWindow()
    ui = Ui_Es_mod_namager_linux()
    ui.setupUi(Es_mod_namager_linux)
    Es_mod_namager_linux.show()
    sys.exit(app.exec_())
